"""Post-generation audit: does the generated curriculum actually cover the uploaded RPS?

This is a READ-ONLY evaluation step. It runs AFTER the planner produced the
curriculum and answers the question: "which RPS materials are covered /
partial / missing, and how aligned is the curriculum overall?".

Output is stored in ``curriculum.curriculum_json["audit"]["rps_coverage"]``
so it can be inspected from the DB, the curriculum API response, or the
frontend without any extra request.

Purposely independent from the planner itself (different model, no shared
prompt) so it can be used as a sanity check instead of rubber-stamping the
planner's own output.
"""
from __future__ import annotations

import json
import logging

from pydantic import BaseModel, Field

from app.config import settings
from app.utils.llm_factory import get_llm, uses_json_mode

logger = logging.getLogger(__name__)


# ════════════════════════════════════════════════════════════════════════
# Schemas
# ════════════════════════════════════════════════════════════════════════

class CoverageItem(BaseModel):
    """Alignment verdict for a single RPS material."""
    rps_material: str = Field(
        description="Name of the RPS material/weekly topic being judged."
    )
    covered: str = Field(
        description="One of: covered | partial | missing."
    )
    mapped_weeks: list[int] = Field(
        default_factory=list,
        description="Curriculum week number(s) that cover this material. Empty if missing.",
    )
    note: str = Field(
        default="",
        description="1 short sentence justifying the verdict.",
    )


class RpsCoverageReport(BaseModel):
    """Coverage report comparing RPS material vs generated curriculum."""
    total_items: int
    covered_items: int
    partial_items: int
    missing_items: int
    alignment_score: float = Field(
        ge=0.0, le=100.0,
        description="0-100 overall alignment. 100 = every RPS material covered.",
    )
    items: list[CoverageItem]


VERIFY_PROMPT = """You are an objective curriculum alignment auditor.

You are given:
1. RPS_REFERENCE: the weekly teaching plan (Minggu → Bahan Kajian / Sub-CPMK) of a course syllabus.
2. CURCURRICULUM: the structured learning curriculum generated by another AI for the SAME course.

TASK
For EACH material listed in the RPS weekly plan, decide whether the generated
curriculum covers it:

- "covered": material clearly appears (same or near-identical concept) in one or more curriculum weeks.
- "partial": related, but the curriculum only touches part of the material (e.g. the concept itself is there but key sub-topics are skipped).
- "missing": the material does not appear at all in any curriculum week or daily topic.

RULES
1. Judge by semantic meaning, not exact wording. Translations/language differences are fine.
2. Fill `mapped_weeks` with the curriculum week number(s) where the material lives (empty list if missing).
3. Ignore administrative sections (UTS/UAS, grading, assignments). Only judge teaching materials.
4. Compute alignment_score = percent of RPS materials that are covered or partial, weighted so "covered" counts full and "partial" counts half:
   alignment_score = 100 * (covered_items + 0.5 * partial_items) / total_items
5. Be strict but fair: a curriculum that omits core materials (e.g. an entire protocol layer) MUST score "missing" for those.

Return valid JSON only, matching this schema:
{{
  "total_items": int,
  "covered_items": int,
  "partial_items": int,
  "missing_items": int,
  "alignment_score": float,
  "items": [
    {{
      "rps_material": "...",
      "covered": "covered|partial|missing",
      "mapped_weeks": [int, ...],
      "note": "1 sentence"
    }}
  ]
}}

# RPS_REFERENCE (teaching materials only, may be truncated)
{rps_material}

# CURRENT_GENERATED_CURRICULUM
{curriculum_json}
"""


# ════════════════════════════════════════════════════════════════════════
# Public API
# ════════════════════════════════════════════════════════════════════════

def _extract_curriculum_overview(curriculum_json: dict) -> str:
    """Shrink the full curriculum dict to titles only (weeks + daily topics)."""
    weeks = curriculum_json.get("weeks", [])
    lines = []
    for w in weeks:
        topics = [d.get("title", "") for d in w.get("days", [])]
        lines.append(f"Week {w.get('week')}: {w.get('title','')}")
        for t in topics:
            lines.append(f"  - {t}")
    return "\n".join(lines)


async def verify_rps_coverage(rps_text: str, curriculum_json: dict) -> dict:
    """Compare ``curriculum_json`` against the uploaded RPS text.

    Returns the serialized :class:`RpsCoverageReport`. Raises on LLM failure
    so the caller can decide to skip silently.
    """
    # Find the weekly teaching plan of the RPS: it is usually in the table
    # rows starting at 'Minggu' / 'Bahan Kajian'. We pass a bounded slice —
    # full RPS (incl. grading schemes) only adds noise and tokens.
    # Fallback: whole text.
    rps_material = rps_text
    idx = rps_text.find("Minggu")
    if idx >= 0:
        rps_material = rps_text[idx : idx + 12000]

    overview = _extract_curriculum_overview(curriculum_json)
    prompt = VERIFY_PROMPT.format(
        rps_material=rps_material,
        curriculum_json=overview,
    )

    llm = get_llm(settings.RPS_VERIFY_MODEL, temperature=0.0, timeout=120)
    if uses_json_mode(llm):
        structured = llm.with_structured_output(
            RpsCoverageReport, method="json_mode"
        )
    else:
        structured = llm.with_structured_output(RpsCoverageReport)

    from langchain_core.messages import SystemMessage, HumanMessage
    raw = await structured.ainvoke([
        SystemMessage(
            content="You are a rigorous, neutral curriculum audit. Output ONLY the JSON report."
        ),
        HumanMessage(content=prompt),
    ])
    report: RpsCoverageReport = raw

    logger.info(
        "[RPS-VERIFY] alignment=%s%% (%d covered / %d partial / %d missing of %d)",
        report.alignment_score, report.covered_items, report.partial_items,
        report.missing_items, report.total_items,
    )
    return report.model_dump()