"""add_language_preference_to_users

Revision ID: 09fcc06983f1
Revises: 9d6d10f0f32d
Create Date: 2026-06-26 15:51:38.734099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09fcc06983f1'
down_revision: Union[str, Sequence[str], None] = '9d6d10f0f32d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language_preference', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language_preference')
    # ### end Alembic commands ###
