"""refactor_db_remove_metrics_merge_mastery

Revision ID: 7d57968535ad
Revises: a6e556951e36
Create Date: 2026-06-13 16:46:27.470896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d57968535ad'
down_revision: Union[str, Sequence[str], None] = 'a6e556951e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ux_surveys')
    op.drop_table('agent_logs')
    op.drop_table('mastery_scores')
    op.drop_table('rag_metrics')
    op.add_column('topics', sa.Column('mastery_score', sa.Float(), nullable=True))
    op.add_column('topics', sa.Column('quiz_score', sa.Float(), nullable=True))
    op.add_column('topics', sa.Column('reading_time_ratio', sa.Float(), nullable=True))
    op.add_column('topics', sa.Column('question_frequency_score', sa.Float(), nullable=True))
    op.add_column('topics', sa.Column('self_assessment_score', sa.Float(), nullable=True))
    op.add_column('topics', sa.Column('material_rating_score', sa.Float(), nullable=True))
    op.add_column('topics', sa.Column('feedback_action', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'feedback_action')
    op.drop_column('topics', 'material_rating_score')
    op.drop_column('topics', 'self_assessment_score')
    op.drop_column('topics', 'question_frequency_score')
    op.drop_column('topics', 'reading_time_ratio')
    op.drop_column('topics', 'quiz_score')
    op.drop_column('topics', 'mastery_score')
    op.create_table('rag_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('faithfulness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('answer_relevancy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('context_recall', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('context_precision', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('answer_correctness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chunks_retrieved', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chunks_after_rerank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], name=op.f('rag_metrics_message_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], name=op.f('rag_metrics_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rag_metrics_pkey'))
    )
    op.create_table('mastery_scores',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('topic_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('mastery_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quiz_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reading_time_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('question_frequency_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('self_assessment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('material_rating_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('feedback_action', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('calculated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], name=op.f('mastery_scores_session_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('mastery_scores_topic_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mastery_scores_pkey'))
    )
    op.create_table('agent_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('agent', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], name=op.f('agent_logs_session_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_logs_pkey'))
    )
    op.create_table('ux_surveys',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ease_of_use', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('material_relevance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quiz_quality', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('adaptivity_satisfaction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('overall_satisfaction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('open_feedback', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], name=op.f('ux_surveys_session_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ux_surveys_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ux_surveys_pkey'))
    )
    # ### end Alembic commands ###
