"""add_resource_links_table

Revision ID: a6e556951e36
Revises: 1112802827dc
Create Date: 2026-05-19 10:01:03.869709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e556951e36'
down_revision: Union[str, Sequence[str], None] = '1112802827dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=True),
    sa.Column('topic_id', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('link_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('price_type', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('instructor', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('relevant_section', sa.String(), nullable=True),
    sa.Column('embed_mode', sa.String(length=10), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['learning_modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resource_links')
    # ### end Alembic commands ###
