"""add enhanced_mindmap_json column to curricula

Revision ID: h8i9j0k1l2m3
Revises: g7h8i9j0k1l2
Create Date: 2026-06-19 15:30:00.000000

Adds a single nullable JSONB column ``enhanced_mindmap_json`` to
the ``curricula`` table.

Why a new column instead of replacing ``mindmap_json`` /
``concept_graph_json``:

  * Backward compatibility. Existing users who already have a
    ``mindmap_json`` / ``concept_graph_json`` rendered will keep
    their working view; the new column is opt-in.
  * Two different output shapes. The old columns store either
    Mermaid syntax (for the static renderer) or a flat concept
    list (for the React Flow overview view). The new column
    stores a 3-level NotebookLM-style theme→concept→key_point
    structure that powers the new "enhanced" view.
  * Independent cache invalidation. The old mindmap is generated
    eagerly at pipeline time (in the parallel branch right after
    the planner). The new mindmap is generated lazily AFTER the
    first module is composed, by a background Celery task that
    scrapes 1-2 sources per topic. Their cache lifetimes and
    regeneration triggers are decoupled, so they live in separate
    columns.

Generated by a Celery background task (``generate_enhanced_mindmap``)
that runs:
  1. lightweight_researcher  (1-2 Tavily + Jina sources per topic)
  2. mindmap_v2_mapper       (LLM structured output, 3-level schema)
  3. JSONB write here

The frontend's ``/mindmap-data`` endpoint reads this column when
present; otherwise it falls back to the old ``mindmap_json`` /
``concept_graph_json``.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision = "h8i9j0k1l2m3"
down_revision = "g7h8i9j0k1l2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "curricula",
        sa.Column(
            "enhanced_mindmap_json",
            JSONB,
            nullable=True,
        ),
    )


def downgrade() -> None:
    op.drop_column("curricula", "enhanced_mindmap_json")
